name: Build

on:
  workflow_dispatch:
    inputs:
      build_environment:
        type: choice
        options:
          - development
          - production
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "MyGame" src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Game-EXE
        path: dist/
